theme {
    color_scheme = ~/.local/share/color-schemes/noctalia.colors
    icon_theme = kora
    font_fixed = JetBrains Mono
    font_fixed_size = 10
    font = JetBrains Mono
    font_size = 10
}

misc {
    single_click_activate = 1
    menus_have_icons = 1
    shortcuts_for_context_menus = 1
}
