-- Hyprland configuration main entry point.
-- Loads monitors, Orbit presentation settings, and session lifecycle.
--
-- Border and group colours are applied by Noctalia's generated hyprland.lua template.
--
-- Theme colours are regenerated by Noctalia's configured templates.

local home = os.getenv("HOME")
package.path = home .. "/.config/hypr/?.lua;" .. package.path

-- Application launcher paths: terminal, file manager, app menu, utility scripts.
local terminal = "ghostty"
local fileManager = "dolphin"
local launcher = "noctalia msg panel-toggle launcher"
local chatGPT = "chatgpt"
local scripts = home .. "/.config/hypr/scripts"
local gpuScreenRecorder = home .. "/.local/bin/gpu-screen-recorder-control"
local animateLock = scripts .. "/animate-lock"
local animateShutdown = scripts .. "/animate-shutdown"
local workspaceAltTab = home .. "/.local/bin/workspace-alt-tab"
local moveWindowWorkspace = scripts .. "/move-window-workspace"
local focusWorkspace = scripts .. "/focus-workspace"
local focusDirectional = scripts .. "/focus-directional"

-- Modifier key for all Hyprland keybindings.
local mainMod = "SUPER"

-- Third-party Hyprland plugins: Hyprglass (blur/glass effects) and HyprWindowShade (ripple animations).
local hyprGlassPlugin = home .. "/.local/share/hyprland/plugins/hyprglass.so"
local hyprWindowShadePlugin = home .. "/.local/share/hyprland/plugins/HyprWindowShade.so"
local scrollOverviewPlugin = home .. "/.local/share/hyprland/plugins/libscrolloverview.so"
local dynamicCursorsPlugin = home .. "/.local/share/hyprland/plugins/dynamic-cursors.so"

-- Compositor policy is maintained here; generated appearance adapters are not
-- configuration inputs.
local orbitAppearance = {
    shape = { corner_radius = 11, window_radius = 11 },
    transparency = { compositor = { active_opacity = 1.0, inactive_opacity = 0.95 } },
    effects = {
        hyprglass_enabled = true,
        hyprglass_blur_type = "glass",
        animations_enabled = true,
        animations = {
            global = { enabled = true, speed = 4.8, type = "default" },
            windows = { enabled = true, speed = 1.3, type = "slide" },
            fades = { enabled = true, speed = 1.1, type = "fade" },
            layers = { enabled = true, speed = 1.8, type = "fade" },
            workspaces = { enabled = true, speed = 1.1, type = "slidefadevert" },
            movement = { enabled = true, speed = 1.2, type = "slide" },
        },
    },
}
local orbitCursor = { theme = "oblique-cursor", size = 24 }
local hyprcursorTheme = "oblique-cursor"
local xcursorFallbackTheme = "Adwaita"
local cursorSize = orbitCursor.size or 24
local orbitShape = orbitAppearance.shape or { corner_radius = 10, window_radius = 10 }

local orbitFollowMouse = 2

-- Map Orbit animation style names to Hyprland animation parameters.
-- Orbit uses generic names (default, slidefadevert, popin); Hyprland needs full syntax.
local function animation_style(kind, fallback)
    if kind == "default" or kind == nil then return fallback end
    if kind == "slidefadevert" then return "slidefadevert -100%" end -- Vertical slide + fade
    if kind == "popin" then return "popin 80%" end                   -- Zoom-in effect at 80% start size
    return kind
end
-- Read dynamic lock screen background color from Orbit Wallpaper Engine.
-- The wallpaper shader generates hyprlock-background.conf with the current dominant color.
-- Fallback to hard-coded dark color if file does not exist.
local hyprlockBackgroundColor = "rgb(050508)"
local hyprlockBackgroundFile = io.open(home .. "/.cache/orbit-wallpaper-engine/hyprlock-background.conf", "r")
if hyprlockBackgroundFile then
    local contents = hyprlockBackgroundFile:read("*a")
    hyprlockBackgroundFile:close()
    local color = contents:match("color%s*=%s*rgb%((%x+)%)")
    if color then hyprlockBackgroundColor = "rgb(" .. color .. ")" end
end

-- Load monitor configuration generated by nwg-displays. It is machine-local and
-- absent before nwg-displays has run, so a failure here must not take down the
-- rest of the configuration.
local monitorsLoaded = pcall(require, "monitors")
if not monitorsLoaded then
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end
-- The plugin's config namespace is unavailable during the initial parse. The
-- startup hook loads the plugin and performs a config-only reload afterward.
if hl.plugin.scrolloverview then
    require("scrolloverview")
end

-- Environment and permissions
-- These variables configure the look and behavior of Qt6 applications.
local function prepend_path_entry(path, entry)
    if (":" .. path .. ":"):find(":" .. entry .. ":", 1, true) then return path end
    return entry .. ":" .. path
end
local sessionPath = os.getenv("PATH") or "/usr/local/bin:/usr/bin"
sessionPath = prepend_path_entry(sessionPath, home .. "/bin")
sessionPath = prepend_path_entry(sessionPath, home .. "/.local/bin")
hl.env("PATH", sessionPath)                        -- Keep user tools discoverable in graphical and systemd scopes.

-- NVIDIA proprietary/open driver environment. Applied only on NVIDIA hosts so the
-- same configuration stays correct on machines without one.
local nvidiaVersionFile = io.open("/proc/driver/nvidia/version", "r")
if nvidiaVersionFile then
    nvidiaVersionFile:close()
    hl.env("NVD_BACKEND", "direct")
    hl.env("LIBVA_DRIVER_NAME", "nvidia")
    hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
end
hl.env("HYPRCURSOR_THEME", hyprcursorTheme)        -- Canonical compositor/server-side cursor.
hl.env("HYPRCURSOR_SIZE", tostring(cursorSize))    -- Keep compositor and client cursor sizes aligned.
hl.env("XCURSOR_THEME", xcursorFallbackTheme)       -- Existing XCursor fallback for legacy clients.
hl.env("XCURSOR_SIZE", tostring(cursorSize))        -- X11 cursor compatibility adapter.
-- Qt platform theme. Orbit's Qt adapters target hyprqt6engine, and
-- orbit-session-bootstrap requires this variable to be set before it will import
-- the session environment and start hyprland-session.target. Fedora sets it
-- globally; Arch does not, so the compositor must.
hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")
-- Allow hyprpm (Hyprland plugin manager) to load/unload plugins without sudo.
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-- Session lifecycle: startup and shutdown hooks.

hl.on("hyprland.start", function()
    -- Only the explicit new-workspace application allowlist gets automatic
    -- workspace allocation. Ordinary windows are never routed by a daemon.
    -- Import the current session environment, start target-owned services once,
    -- run the login transition, and rebind the Hyprland portal after compositor
    -- readiness is confirmed.
    hl.exec_cmd(home .. "/.local/bin/orbit-session-bootstrap &")

    -- Start Noctalia from the graphical session so applications it launches
    -- inherit the active logind session rather than the user service cgroup.
    hl.exec_cmd("/usr/bin/noctalia &")

    -- Start the global-menu frontend after the Wayland compositor is ready.
    -- The executable is supplied by PATH, or by ORBIT_QUICKSHELL when a local
    -- installation is not on the graphical session PATH.
    local quickshell = os.getenv("ORBIT_QUICKSHELL") or "quickshell"
    hl.exec_cmd(quickshell .. " --config global-menu --no-duplicate &")

    -- Explicit orbit-game-run sessions own game-mode policy.

    -- Load plugins and refresh the compositor config. Sequence:
    -- 1. Reload hyprpm (plugin manager)
    -- 2. Load Hyprglass plugin (blur/glass effect)
    -- 3. Load HyprWindowShade plugin (ripple animations)
    -- 4. Brief sleep to allow plugin initialization
    -- 5. Reload config (pick up plugin availability)
    -- 6. Leave target-owned Orbit shell lifecycle under systemd
    hl.exec_cmd([[sh -c 'hyprpm reload 2>/dev/null || true; hyprctl plugin load ]] ..
    hyprGlassPlugin ..
    [[ 2>/dev/null || true; hyprctl plugin load ]] ..
     hyprWindowShadePlugin ..
     [[ 2>/dev/null || true; hyprctl plugin load ]] ..
     scrollOverviewPlugin ..
     [[ 2>/dev/null || true; hyprctl plugin load ]] ..
     dynamicCursorsPlugin .. [[ 2>/dev/null || true; sleep 0.5; hyprctl reload config-only']])
end)

-- Core behavior and appearance (window manager tuning).

hl.config({
    general = {
        gaps_in = 5,     -- Spacing between tiled windows (pixels).
        gaps_out = 20,   -- Spacing from windows to workspace edge (pixels).
        border_size = 2, -- Window border thickness (pixels).
        col = {
            -- Border colours are applied by Noctalia's generated theme template below.
        },
        resize_on_border = true,      -- Allow drag-resizing from window borders.
        extend_border_grab_area = 20, -- Enlarge the border grab area for easier resizing.
        allow_tearing = false,        -- Disable tear-free rendering (VSync enabled).
        layout = "master",            -- Use master layout: main + stack columns.
    },

    decoration = {
         rounding = orbitShape.window_radius or orbitShape.corner_radius,                          -- Compositor appearance policy.
        rounding_power = 2,                                                                       -- Curvature smoothness (2 = smoother).
        active_opacity = orbitAppearance.transparency.compositor.active_opacity,                  -- Active window opacity (1.0 = opaque).
        inactive_opacity = orbitAppearance.transparency.compositor.inactive_opacity,              -- Inactive window opacity (0.95 default).
        blur = { enabled = orbitAppearance.effects.hyprglass_enabled, new_optimizations = true }, -- Hyprglass blur if enabled.
        shadow = { enabled = true, range = 2, render_power = 5, color = 0xee1a1a1a },             -- Soft dark shadow beneath windows.
        motion_blur = { enabled = true, samples = 20 },
    },

    -- Global animation toggle (individual animations have their own enable flags).
    animations = { enabled = orbitAppearance.effects.animations_enabled },

    input = {
        kb_layout = "us,ara",                  -- US and Arabic layouts.
        kb_options = "grp:alt_shift_toggle",   -- Alt+Shift switches between them.
        follow_mouse = orbitFollowMouse,       -- Follow mouse mode (0=off, 1=speed-1, 2=speed-2 from Orbit).
        mouse_refocus = false,                 -- Do not refocus windows when moving the mouse.
        sensitivity = 0,                       -- Mouse sensitivity (0 = use system default).
        touchpad = { natural_scroll = false }, -- Touchpad scroll direction (false = traditional).
    },

    cursor = {
        no_warps = true, -- Do not move cursor when switching windows (preserve position).
        sync_gsettings_theme = false, -- Keep Adwaita for XCursor/GTK while Hyprcursor uses Oblique.
    },

    misc = {
        force_default_wallpaper = 0,                -- Do not use Hyprland's default wallpaper.
        background_color = hyprlockBackgroundColor, -- Fallback background (from Orbit Wallpaper Engine or hard-coded).
        disable_hyprland_logo = true,               -- Hide "Hyprland" text splash.
        focus_on_activate = true,                   -- Focus windows when they request activation (e.g., notification clicks).
        animate_manual_resizes = true,              -- Animate window resizing when user drags.
        disable_splash_rendering = true,            -- Hide splash screen on startup.
    },

    binds = {
        window_direction_monitor_fallback = true, -- Allow focus to cross monitor boundaries with arrow keys.
        pass_mouse_when_bound = true,             -- Pass mouse events to windows even when a keybind is active.
    },

    -- Master layout: first window occupies a fixed main area on the left; subsequent windows stack on the right.
    -- This is ideal for a primary editor + auxiliary windows setup.
    master = {
        mfact = 0.7,                                 -- Main area factor (70% width for the main window).
        new_status = "slave",                        -- New windows start in the stack area, not main.
        orientation = "left",                        -- Main area on the left; stack on the right.
    },
    scrolling = { fullscreen_on_one_column = true }, -- Fullscreen if only one window in a column.
})

-- Dynamic cursor effects are optional so a missing or failed plugin never adds
-- unknown Hyprland configuration keys during the initial parse.
if hl.plugin.dynamic_cursors then
    hl.config({
        plugin = {
            dynamic_cursors = {
                enabled = true,
                mode = "tilt",
                shake = {
                    enabled = true,
                    threshold = 6.0,
                    base = 2.5,
                    speed = 3.0,
                    influence = 0.0,
                    limit = 4.0,
                    timeout = 1600,
                    effects = false,
                    ipc = false,
                },
                hyprcursor = {
                    enabled = true,
                    nearest = 0,
                    resolution = 192,
                    fallback = "clientside",
                },
            },
        },
    })
end


-- Hyprglass plugin: blur and glass effects for windows and layers.
-- Plugin is loaded dynamically on startup; only configure if present.
if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        default_theme = "dark",                                        -- Use dark theme (less bright refraction artifacts).
        default_preset = orbitAppearance.effects.hyprglass_blur_type,  -- Compositor-owned preset.
        -- Orbit layer-shell surfaces use native Hyprland blur. Hyprglass
        -- remains enabled for normal application windows.
        layers = { enabled = 0 },
    })

    -- "Glass" preset: high refraction and distortion for a glossy, transparent look.
    hg.preset("glass", {
        glass_opacity = 1,          -- Fully opaque glass (no extra transparency).
        blur_strength = 0.7,        -- Strong blur effect (0-1).
        blur_iterations = 3,        -- Number of blur passes (higher = more blur, more expensive).
        refraction_strength = 1,    -- Distortion from refraction (refracts light rays).
        chromatic_aberration = 0.5, -- Color separation at edges (0.5 = medium aberration).
        edge_thickness = 0.1,       -- Thickness of the refraction edge effect.
        lens_distortion = 0.9,      -- Barrel/pincushion distortion (0.9 = slight barrel).
        brightness = 1.1,           -- Brighten the blurred content slightly.
        contrast = 1.4,             -- Increase contrast (makes blurred content more visible).
    })
end

-- Animation curves: define timing functions for smooth motion.
-- Bezier curves: fast startup (ease-out), smooth middle (in-out), fast exit (quick).
-- Spring curve: adds bounce/overshoot for a more natural feel.
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })         -- Fast start, slow end.
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })    -- Slow start/end, fast middle.
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })                     -- Constant speed.
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })        -- Nearly constant, slight ease-in.
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })                 -- Very fast (sharp acceleration).
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 }) -- Springy, bouncy motion.
hl.curve("orbitTunedB", { type = "spring", mass = 1, stiffness = 360, dampening = 22 })         -- Tuned motion/workspace spring.

-- Global animation timing (affects all animation speed multipliers).
hl.animation({ leaf = "global", enabled = orbitAppearance.effects.animations.global.enabled, speed = orbitAppearance
.effects.animations.global.speed, bezier = "default" })

-- Border color transitions when switching focus.
hl.animation({ leaf = "border", enabled = orbitAppearance.effects.animations.global.enabled, speed = 5.39, bezier =
"easeOutQuint" })

-- Window size/position changes. Use almostLinear to keep them smooth without fighting workspace transitions.
hl.animation({ leaf = "windows", enabled = orbitAppearance.effects.animations.windows.enabled, speed = orbitAppearance
.effects.animations.windows.speed, spring = "orbitTunedB" })

-- Disable windowsIn (new window entry animation) to prevent double-animation with fadeIn.
-- Client surface remains still; opacity fade alone provides entrance effect.
hl.animation({ leaf = "windowsIn", enabled = false, speed = 4.1, spring = "easy", style = animation_style(
orbitAppearance.effects.animations.windows.type, "popin 80%") })

-- Window exit animation (slide out on close).
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.95, spring = "orbitTunedB", style = animation_style(
orbitAppearance.effects.animations.windows.type, "slide") })

-- Opacity fade-in for new windows (entrance effect).
hl.animation({ leaf = "fadeIn", enabled = orbitAppearance.effects.animations.fades.enabled, speed = orbitAppearance
.effects.animations.fades.speed, bezier = "almostLinear" })

-- Opacity fade-out for closing windows.
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.25, bezier = "almostLinear" })

-- Generic fade transitions (dialogs, menus, etc.).
hl.animation({ leaf = "fade", enabled = orbitAppearance.effects.animations.fades.enabled, speed = 3.03, bezier = "quick" })

-- Layer animations (UI panels, notifications, OSD).
hl.animation({ leaf = "layers", enabled = orbitAppearance.effects.animations.layers.enabled, speed = orbitAppearance
.effects.animations.layers.speed, bezier = "easeOutQuint" })

-- Layer entrance animation (fade-in for panels).
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = animation_style(
orbitAppearance.effects.animations.layers.type, "fade") })

-- Layer exit animation (fade-out for panels).
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = animation_style(
orbitAppearance.effects.animations.layers.type, "fade") })

-- Opacity fade for layers (additional effect on top of layersIn/Out).
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })

-- Window movement (drag-to-move, layout adjustments).
hl.animation({ leaf = "windowsMove", enabled = orbitAppearance.effects.animations.movement.enabled, speed =
orbitAppearance.effects.animations.movement.speed, spring = "orbitTunedB", style = animation_style(
orbitAppearance.effects.animations.movement.type, "slide") })

-- Workspace transitions: use the pronounced ease-out curve in both directions so
-- the scene leaves decisively and settles visibly without bounce or overshoot.
hl.animation({ leaf = "workspaces", enabled = orbitAppearance.effects.animations.workspaces.enabled, speed =
orbitAppearance.effects.animations.workspaces.speed, spring = "orbitTunedB", style = animation_style(
orbitAppearance.effects.animations.workspaces.type, "slidefadevert -100%") })
hl.animation({ leaf = "workspacesIn", enabled = orbitAppearance.effects.animations.workspaces.enabled, speed = 2.45, spring =
"orbitTunedB", style = animation_style(orbitAppearance.effects.animations.workspaces.type, "slidefadevert -100%") })
hl.animation({ leaf = "workspacesOut", enabled = orbitAppearance.effects.animations.workspaces.enabled, speed = 2.0, spring =
"orbitTunedB", style = animation_style(orbitAppearance.effects.animations.workspaces.type, "slidefadevert -100%") })

-- Zoom factor: used for workspace overview or active indicator scaling.
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Keybindings (main modifier: Super key)
-- Application launchers
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))         -- Open terminal (ghostty).
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))           -- Open file manager (nautilus).
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(chatGPT))               -- Open ChatGPT.
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(launcher))          -- Open the Noctalia launcher.
hl.bind("ALT + TAB", hl.dsp.exec_cmd(workspaceAltTab .. " cycle")) -- Workspace-oriented ScrollOverview switcher.

-- Window management
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd(workspaceAltTab .. " close"))                 -- Close ScrollOverview if open.
hl.bind(mainMod .. " + C", hl.dsp.window.close())                                             -- Close active window.
hl.bind(mainMod .. " + Q", hl.dsp.window.close())                                             -- Close active window (Ayzrch).
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))                        -- Toggle float/tile for active window.
hl.bind("ALT + Return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })) -- Toggle fullscreen.

-- Session control
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(animateLock))     -- Lock screen with animation.
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(animateShutdown)) -- Shutdown session with animation.

-- Screenshots and recording
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | satty --filename -]])) -- Screenshot (select region, annotate in satty).
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd(gpuScreenRecorder .. " record"))                      -- Start GPU screen recording.
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd(gpuScreenRecorder .. " replay"))                      -- Save instant replay (last 30s).

-- System monitoring
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("flatpak run io.missioncenter.MissionCenter")) -- Open Mission Center (system monitor).

-- Placement diagnostics

-- Directional focus shares monitor geometry with Super+Shift+Arrow movement.
for key, direction in pairs({ left = "l", right = "r", up = "u", down = "d" }) do
    hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(focusDirectional .. " " .. direction))
end

-- Scroll wheel on window also focuses vertically (when mouse is over the window).
for key, direction in pairs({ mouse_up = "u", mouse_down = "d" }) do
    hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(focusWorkspace .. " " .. direction), { mouse = true })
end

-- One directional dispatcher handles intra-workspace movement, monitor edges,
-- and workspace-hierarchy edges for all four arrows.
for key, direction in pairs({ left = "l", right = "r", up = "u", down = "d" }) do
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.exec_cmd(moveWindowWorkspace .. " " .. direction),
        { repeating = true })
end

-- Resize active window: SUPER + CTRL + arrow keys. Repeating = hold to continuously resize.
-- Delta values: ±40 pixels per key press (relative resizing).
for key, delta in pairs({
    left = { x = -40, y = 0 }, -- Shrink width.
    right = { x = 40, y = 0 }, -- Grow width.
    up = { x = 0, y = -40 },   -- Shrink height.
    down = { x = 0, y = 40 },  -- Grow height.
}) do
    hl.bind(mainMod .. " + CTRL + " .. key, hl.dsp.window.resize({ x = delta.x, y = delta.y, relative = true }),
        { repeating = true })
end

-- Ayzrch additions
-- Orbit has no numbered workspace binds: it addresses workspaces semantically
-- through the Home blocks and directional movement. Absolute switching coexists
-- with that, and workspace 1/6/11... remain each monitor's Home.
for index = 1, 10 do
    local key = tostring(index % 10)
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = index }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = index }))
end

-- Scratchpad special workspace.
hl.bind(mainMod .. " + grave", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + grave", hl.dsp.window.move({ workspace = "special:magic" }))

-- Maximize. Alt+Return remains true fullscreen.
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

-- Browser profiles. Zen registers these in ~/.config/zen/profiles.ini.
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("zen-browser -P Personal"))          -- Personal profile.
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("zen-browser -P Work"))      -- Work profile.

-- Utilities.
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher /emo")) -- Emoji picker.
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))                -- Colour picker to clipboard.

-- Audio, media and brightness keys. `repeating` holds to repeat; `locked` keeps
-- them working while the lock screen is up.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Mouse-based window management
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })   -- SUPER + left-click-drag: move window.
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true }) -- SUPER + right-click-drag: resize window.

-- Double-click window title bar to toggle float/tile (uses toggle-float-double-click script).
hl.bind("mouse:272", hl.dsp.exec_cmd(scripts .. "/toggle-float-double-click"), { mouse = true })

-- Window rules

-- Applications stay on the workspace where they were launched and float by default.
hl.window_rule({
    name = "default-floating",
    match = { class = ".*" },
    float = true,
})

-- Affinity is launched through XWayland, but remains usable in the normal
-- tiled layout instead of inheriting the generic floating default.
hl.window_rule({
    name = "affinity-tiled",
    match = { class = "^affinity\\.exe$", title = ".+", xwayland = true },
    float = false,
})

-- The only automatic workspace placement exceptions. The narrow event helper
-- allocates one normal workspace for these exact classes and nothing else.
for _, class in ipairs({ "^zen$", "^dev\\.zed\\.Zed$" }) do
    hl.window_rule({
        name = "new-workspace-app-" .. class,
        match = { class = class },
        float = false,
    })
end

-- Window rule: Steam games (full-screen optimizations).
-- Games are marked with content="game" to exclude them from game-mode detection and effects.
hl.window_rule({
    name = "steam-games",
    match = { class = "^steam_app_.*" },
    immediate = true,          -- Apply rule as soon as window is identified (not after mapping).
    no_anim = true,            -- Disable window animations (for smoother gameplay).
    no_blur = true,            -- Disable Hyprglass blur effects.
    no_shadow = true,          -- Disable drop shadow.
    decorate = false,          -- Hide window decorations (remove title bar).
    content = "game",          -- Mark as game content (used by game-mode detection).
    float = false,             -- Preserve normal tiled game clients; no workspace routing.
    no_follow_mouse = true,    -- Do not refocus when mouse moves (preserve game control).
    focus_on_activate = false, -- Do not auto-focus activation requests (reduce distractions).
})

-- Zed supplies its transparent chrome through the tracked theme; keep the
-- client surface fully opaque so only those internal surfaces reveal the
-- wallpaper.
-- Window rule: Zed code editor appearance.
-- Zed uses transparent chrome and tracks the Hyprland theme to show only internal surfaces.
-- Keep the client window opaque (no extra transparency from Hyprland).
hl.window_rule({
    name = "zed-appearance",
    match = { class = "^dev\\zed\\Zed$" },
    rounding = orbitShape.window_radius or orbitShape.corner_radius,
    no_shadow = true, -- Remove shadow (Zed provides its own).
})

-- Window rule: Obsidian note editor appearance.
-- Obsidian uses a similar tracked theme approach: transparent chrome, opaque editor.
-- Ensure consistent appearance with other modern applications.
hl.window_rule({
    name = "obsidian-appearance",
    match = { class = "^md\\obsidian\\Obsidian$" },
    rounding = orbitShape.window_radius or orbitShape.corner_radius,
    decorate = false, -- Remove Hyprland decoration (Obsidian provides its own frame).
    no_shadow = true, -- No shadow (Obsidian renders its own if needed).
})

-- Window rule: Steam menu windows and popups (float).
-- Steam opens many transient windows (downloads, settings, etc.).
hl.window_rule({
    name = "steam-transient-windows",
    match = { class = "^steam$" },
    float = true, -- Float by default (main Steam window overridden below).
})

-- Window rule: Steam main window (keep tiled).
-- The main Steam window (title="Steam") should be tiled, not floated.
hl.window_rule({
    name = "keep-steam-main-window-tiled",
    match = { class = "^steam$", title = "^Steam$" },
    float = false,    -- Override: main window is tiled (respects layout manager).
    decorate = false, -- No window decoration (Steam provides its own UI).
})

-- Window rule: WezTerm terminal sizing.
hl.window_rule({
    name = "wezterm-sizing",
    match = { class = "^org\\.wezfurlong\\.wezterm$" },
    float = false,
    size = { 800, 600 },    -- Default new window size (wide for 80-col terminal + UI).
    center = true,          -- Center on current monitor.
    persistent_size = true, -- Remember size across launches.
})

-- Window rule: About This Computer Fastfetch terminal.
-- The launcher assigns this dedicated class so ordinary WezTerm windows are unaffected.
hl.window_rule({
    name = "orbit-about-sizing",
    match = { class = "^orbit-about$" },
    float = true,
    size = { 534, 262 },
})

-- Keep application keybind targets tiled on their current workspace.
hl.window_rule({
    name = "chatgpt-tiled",
    match = { class = "^Chatgpt$" },
    float = false,
})

hl.window_rule({
    name = "opencode-tiled",
    match = { class = "^orbit-opencode$" },
    float = false,
})

hl.window_rule({
    name = "orbit-notes-tiled",
    match = { class = "^orbit-notes$" },
    float = false,
})

-- Window rule: suppress maximize button events (disabled by default).
-- Some applications emit spurious maximize events; this rule can suppress them.
-- Currently disabled (set_enabled = false) to allow normal maximize behavior.
local suppressMaximizeRule = hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})
suppressMaximizeRule:set_enabled(false) -- Disabled: let maximize work normally.

-- Layer rule: Noctalia UI elements (fallback theme bars, notifications, OSD).
-- NOCTALIA IS A FALLBACK: Only active if the primary Orbit shell fails to start or is disabled.
-- The Noctalia greeter provides basic window management, notifications, and panel when Orbit is unavailable.
-- When this layer matches, it indicates Orbit's shell/panel is not running (error condition).
hl.layer_rule({
    name = "noctalia",
    match = {
        namespace = "^noctalia-(bar-.+|notification|panel|osd|window-switcher)$",
    },
    no_anim = true,   -- Disable animations for fallback UI (lighter rendering = better fallback experience).
    ignore_alpha = 0.5, -- Ignore alpha < 0.5 (fade out effect without full animation opacity change).
})

-- Layer rule: Orbit's top panel (active primary UI).
-- Orbit's global menu grows downward from the panel. Disable animation on the panel's layer
-- or the menu will appear to slide in, breaking the integrated look.
hl.layer_rule({
    name = "orbit-top-panel-no-menu-animation",
    match = { namespace = "^orbit-top-panel$" },
    blur = false,
    no_anim = true, -- Panel resizes without animation (menu appears instantly integrated).
})

-- Native Hyprland owns Orbit menu blur.
hl.layer_rule({
    name = "orbit-menu-glass-native-blur",
    match = { namespace = "^orbit-menu-glass$" },
    blur = true,
    ignore_alpha = 0.01,
    no_anim = false,
})

hl.layer_rule({
    name = "orbit-workspace-indicators-native-blur",
    match = { namespace = "^orbit-workspace-indicators$" },
    blur = true,
    ignore_alpha = 0.01,
})

hl.layer_rule({
    name = "orbit-session-loading-native-blur",
    match = { namespace = "^orbit-session-loading$" },
    blur = true,
    ignore_alpha = 0.01,
})

hl.layer_rule({
    name = "orbit-overview-native-blur",
    match = { namespace = "^orbit-overview$" },
    blur = true,
    ignore_alpha = 0.01,
})

hl.window_rule({
    match = { class = "dev.noctalia.Noctalia" },
    float = true,
    size = { 1080, 920 },
})

hl.layer_rule({
    name = "noctalia",
    match = {
        namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$",
    },
    no_anim = true,
    ignore_alpha = 0.5,
    blur = false,
    blur_popups = false,
})

-- For Noctalia Color templates. The module is generated by Noctalia's Hyprland
-- template and does not exist until Noctalia has run once; border colours simply
-- stay at their defaults until then.
local noctaliaLoaded, noctaliaTheme = pcall(require, "noctalia")
if noctaliaLoaded and type(noctaliaTheme) == "table" and noctaliaTheme.apply_theme then
    noctaliaTheme.apply_theme()
end

-- For Noctalia Color templates
require("noctalia").apply_theme()
