-- Generated by Noctalia. Do not edit manually.
return {
    colors = {
        primary = "{{ colors.primary.default.hex }}",
        secondary = "{{ colors.secondary.default.hex }}",
        surface = "{{ colors.surface.default.hex }}",
        error = "{{ colors.error.default.hex }}",
    },
}
